services:


  JobBoy\Process\Domain\IterationMaker\IterationMaker:
    class: JobBoy\Process\Domain\IterationMaker\IterationMaker
    arguments:
      - '@JobBoy\Process\Domain\Repository\ProcessRepositoryInterface'
      - '@JobBoy\Process\Domain\Lock\LockFactoryInterface'
      - '@JobBoy\Process\Domain\IterationMaker\ProcessIterator'
      - '@JobBoy\Process\Domain\Event\EventBusInterface'