services:
  JobBoy\Process\Console\Command\StartProcessCommand:
    class: JobBoy\Process\Console\Command\StartProcessCommand
    arguments:
      - '@JobBoy\Process\Application\Service\StartProcess'
    tags:
      - { name: 'console.command' }

  JobBoy\Process\Console\Command\WorkCommand:
    class: JobBoy\Process\Console\Command\WorkCommand
    arguments:
      - '@JobBoy\Process\Application\Service\Work'
    tags:
      - { name: 'console.command' }