services:


  JobBoy\Process\Domain\Repository\Infrastructure\Doctrine\ProcessRepository:
    class: JobBoy\Process\Domain\Repository\Infrastructure\Doctrine\ProcessRepository
    arguments:
      - '@JobBoy\Process\Domain\Entity\Factory\ProcessFactory'
      - '@doctrine.dbal.default_connection'


